import { api,dataOf } from "./api"
import type { AktifitasDenganBobot,Indikator,IndikatorBidang,OpsiMaster,SimpanAktifitasInput } from "./types"
type Row={id:number;subkegiatan_id:number;kode_aktifitas:string;nama_aktifitas:string;tipe_aktifitas:"UTAMA"|"PENDUKUNG";satuan:string|null;target_anjuran:number|null;urutan:number;flag_active:boolean}
const map=(r:Row):Indikator=>({id:r.id,indikatorUtamaId:r.subkegiatan_id,kodeIndikator:r.kode_aktifitas,namaIndikator:r.nama_aktifitas,tipeAktifitas:r.tipe_aktifitas,satuan:r.satuan??"",targetAnjuran:Number(r.target_anjuran??0),urutan:r.urutan,flagActive:r.flag_active})
export async function getAktifitasByIndikatorUtama(id:number|null,opsi:OpsiMaster={}):Promise<AktifitasDenganBobot[]>{const rows=dataOf<Row[]>(await api.get("/aktifitas-master",{params:{...(id!=null&&{subkegiatan_id:id}),...(!opsi.termasukNonaktif&&{flag_active:1})}}));const aktif=rows.filter(r=>r.flag_active),n=aktif.filter(r=>r.tipe_aktifitas==="PENDUKUNG").length;return rows.map(r=>({...map(r),bobotTarget:r.tipe_aktifitas==="UTAMA"?70:(n?30/n:0)}))}
export async function getJumlahAktifitas():Promise<number>{return (await getAktifitasByIndikatorUtama(null,{termasukNonaktif:true})).length}
export async function simpanAktifitas(i:SimpanAktifitasInput):Promise<Indikator>{const body={SUBKEGIATAN_ID:i.indikatorUtamaId,KODE_AKTIFITAS:i.kodeIndikator,NAMA_AKTIFITAS:i.namaIndikator,TIPE_AKTIFITAS:i.tipeAktifitas,SATUAN:i.satuan,TARGET_ANJURAN:i.targetAnjuran,FLAG_ACTIVE:true};return map(dataOf<Row>(i.id?await api.put(`/aktifitas-master/${i.id}`,body):await api.post("/aktifitas-master",body)))}
export async function setAktifAktifitas(id:number,aktif:boolean):Promise<Indikator>{const all=await getAktifitasByIndikatorUtama(null,{termasukNonaktif:true});const r=all.find(x=>x.id===id);if(!r)throw new Error("Aktifitas tidak ditemukan.");return map(dataOf<Row>(await api.put(`/aktifitas-master/${id}`,{SUBKEGIATAN_ID:r.indikatorUtamaId,KODE_AKTIFITAS:r.kodeIndikator,NAMA_AKTIFITAS:r.namaIndikator,TIPE_AKTIFITAS:r.tipeAktifitas,SATUAN:r.satuan,TARGET_ANJURAN:r.targetAnjuran,FLAG_ACTIVE:aktif})))}
export async function getIndikatorBidangBySubkegiatanBidang():Promise<IndikatorBidang[]>{return []}
