import { api,dataOf } from "./api"
import type { CapaianDetail,IndikatorBidang,IndikatorUtama,OpsiMaster,SimpanSubkegiatanInput,SubkegiatanBidang } from "./types"
type Row={id:number;kegiatan_id:number;kode_subkegiatan:string;nama_subkegiatan:string;indikator_kinerja:string|null;target_anjuran:number|null;satuan:string|null;output_kinerja:string|null;flag_active:boolean}
const map=(r:Row):IndikatorUtama=>({id:r.id,kegiatanId:r.kegiatan_id,kodeIndikatorUtama:r.kode_subkegiatan,namaIndikatorUtama:r.nama_subkegiatan,indikatorKinerja:r.indikator_kinerja??"",targetKinerja:Number(r.target_anjuran??0),satuanKinerja:r.satuan??"",outputKinerja:r.output_kinerja,flagActive:r.flag_active})
export async function getSubkegiatan(opsi:OpsiMaster={}):Promise<IndikatorUtama[]>{return dataOf<Row[]>(await api.get("/subkegiatan",{params:opsi.termasukNonaktif?{}:{flag_active:1}})).map(map)}
export async function getSubkegiatanById(id:number):Promise<IndikatorUtama|null>{return map(dataOf<Row>(await api.get(`/subkegiatan/${id}`)))}
export async function getSubkegiatanByKegiatan(kegiatanId:number,opsi:OpsiMaster={}):Promise<IndikatorUtama[]>{return dataOf<Row[]>(await api.get("/subkegiatan",{params:{kegiatan_id:kegiatanId,...(!opsi.termasukNonaktif&&{flag_active:1})}})).map(map)}
export async function simpanSubkegiatan(i:SimpanSubkegiatanInput):Promise<IndikatorUtama>{const body={KEGIATAN_ID:i.kegiatanId,KODE_SUBKEGIATAN:i.kodeIndikatorUtama,NAMA_SUBKEGIATAN:i.namaIndikatorUtama,INDIKATOR_KINERJA:i.indikatorKinerja,TARGET_ANJURAN:i.targetKinerja,SATUAN:i.satuanKinerja,OUTPUT_KINERJA:i.outputKinerja,FLAG_ACTIVE:true};return map(dataOf<Row>(i.id?await api.put(`/subkegiatan/${i.id}`,body):await api.post("/subkegiatan",body)))}
export async function setAktifSubkegiatan(id:number,aktif:boolean):Promise<IndikatorUtama>{const r=await getSubkegiatanById(id);if(!r)throw new Error("Subkegiatan tidak ditemukan.");return map(dataOf<Row>(await api.put(`/subkegiatan/${id}`,{KEGIATAN_ID:r.kegiatanId,KODE_SUBKEGIATAN:r.kodeIndikatorUtama,NAMA_SUBKEGIATAN:r.namaIndikatorUtama,INDIKATOR_KINERJA:r.indikatorKinerja,TARGET_ANJURAN:r.targetKinerja,SATUAN:r.satuanKinerja,OUTPUT_KINERJA:r.outputKinerja,FLAG_ACTIVE:aktif})))}
export async function getSubkegiatanByBidang():Promise<SubkegiatanBidang[]>{return []}
export async function getSubkegiatanBidangById():Promise<SubkegiatanBidang|null>{return null}
export async function getCapaian():Promise<CapaianDetail|null>{return null}
export const mapAktifitasTrans=(r:any):IndikatorBidang=>({id:r.id,subkegiatanBidangId:r.subkegiatan_bidang_id??0,masterIndikatorId:r.aktifitas_master_id??0,flagAdhoc:Boolean(r.flag_adhoc),dipakai:r.dipakai??true,tipeAktifitas:r.tipe_aktifitas,namaAktifitas:r.nama_aktifitas,bobotTarget:Number(r.bobot_target),target:Number(r.target),realisasi:Number(r.realisasi),bobotRealisasi:Number(r.bobot_realisasi),urutan:r.urutan})
